name: Pull_Request_Workflow
on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
  
jobs:
  pylint_check:
    uses: ./.github/workflows/pylint.yml
  
  codeql_check:
    needs: pylint_check
    uses: ./.github/workflows/codeql.yml

