name: Pull-Request

on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
  
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')

  upload:
    needs: [pylint,analyze]
    runs-on: ubuntu-latest
    steps:
    - name: Test Python
      run: python --version
      
    
  
