name: Upload_JSON

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  upload_artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Executing the code
      run: python main.py
    - name: Pushing the artifact
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add final.json
        git commit -m "Uploading the artifact"
        git push
